import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  title: { fontSize: 24, marginBottom: 20, textAlign: 'center', color: '#111827' },
  sectionTitle: { fontSize: 18, marginTop: 20, marginBottom: 10, color: '#2563EB', borderBottom: '1 solid #E5E7EB', paddingBottom: 5 },
  text: { fontSize: 11, lineHeight: 1.6, marginBottom: 10, color: '#374151', textAlign: 'justify' },
  
  // Flashcard Styles
  cardContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  card: { width: '48%', border: '1 solid #E5E7EB', padding: 10, borderRadius: 5, marginBottom: 10, backgroundColor: '#F9FAFB' },
  cardLabel: { fontSize: 8, color: '#9CA3AF', marginBottom: 4 },
  cardText: { fontSize: 10, marginBottom: 5 },

  // Quiz Styles
  questionBlock: { marginBottom: 15 },
  questionText: { fontSize: 11, fontWeight: 'bold', marginBottom: 5 },
  optionText: { fontSize: 10, marginLeft: 10, color: '#4B5563' },
  answerText: { fontSize: 10, marginTop: 4, color: '#059669', fontStyle: 'italic' },
  
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, textAlign: 'center', color: '#9CA3AF' },
});

// Define the Types (matching your Store)
interface StudyGuideProps {
  summary: string;
  flashcards: { front: string; back: string }[];
  quiz: { question: string; options: string[]; answer: number }[];
}

export const StudyGuidePDF = ({ summary, flashcards, quiz }: StudyGuideProps) => (
  <Document>
    {/* Page 1: Summary */}
    <Page style={styles.page}>
      <Text style={styles.title}>AI Study Guide</Text>
      <Text style={styles.sectionTitle}>Summary</Text>
      <Text style={styles.text}>
        {summary || "No summary generated."}
      </Text>
      <Text style={styles.footer}>Generated by Your AI App</Text>
    </Page>

    {/* Page 2: Flashcards */}
    <Page style={styles.page}>
      <Text style={styles.sectionTitle}>Flashcards ({flashcards.length})</Text>
      <View style={styles.cardContainer}>
        {flashcards.map((card, i) => (
          <View key={i} style={styles.card}>
            <Text style={styles.cardLabel}>FRONT</Text>
            <Text style={styles.cardText}>{card.front}</Text>
            <Text style={styles.cardLabel}>BACK</Text>
            <Text style={styles.cardText}>{card.back}</Text>
          </View>
        ))}
      </View>
      <Text style={styles.footer}>Generated by Your AI App</Text>
    </Page>

    {/* Page 3: Quiz */}
    <Page style={styles.page}>
      <Text style={styles.sectionTitle}>Practice Quiz ({quiz.length})</Text>
      {quiz.map((q, i) => (
        <View key={i} style={styles.questionBlock}>
          <Text style={styles.questionText}>{i + 1}. {q.question}</Text>
          {q.options.map((opt, optIndex) => (
            <Text key={optIndex} style={styles.optionText}>
              • {opt}
            </Text>
          ))}
          <Text style={styles.answerText}>Correct Answer: {q.options[q.answer]}</Text>
        </View>
      ))}
      <Text style={styles.footer}>Generated by Your AI App</Text>
    </Page>
  </Document>
);